### ISSUE TITLE
Possible RDF Example inconsistency

### ISSUE THREAD

**Issue by elkym** [comicmeta/ComicBookOntology#34]
The example here of RDF/XML, for Daredevil #67 may have an issue.

```
    <!-- Comic Page: Cover of Daredevil (1964) #67 -->
    <cbo:page>
      <rdf:Description rdf:about="http://example.org/issue/Daredevil_1964_67#cover">
        <cbo:pageType rdf:resource="http://comicmeta.org/vocab/CoverPage"></cbo:pageType>
        <cbo:penciller schema:name="Marie Severin"></cbo:penciller>
        <cbo:letterer schema:name="Sam Rosen"></cbo:letterer>
        <cbo:inker schema:name="Bill Everett"></cbo:inker>
      </rdf:Description>     <--------------
    </cbo:page>
    <cbo:coverPage rdf:resource="http://example.org/issue/Daredevil_1964_67#cover"></cbo:coverPage>
  </rdf:Description>
```
The line noted here-- line 54 in the original document, seems to have an additional RDF close tag.
Either I am very much misunderstanding XML, or RDF, or this is an error.

Can you confirm, or explain?

Thanks.

**Comment by elkym** [comment]
Upon closer examination-- I appear to have missed an earlier rdf description that wasn't closed yet-- the page rdf description is nested within the issue description.

I suppose that's a "nevermind then, I'm just up in the night."

**Comment by seanpetiya** [comment]
Thanks for the message! Yes, there are actually three resources (i.e. works) related to Daredevil #67 described in this node; a story (cbo:story), page (cbo:page), and cover page (cbo:coverPage). It's an attempt at describing the artwork, story, etc. (i.e. contents) of a comic book using CBO terms.

The last node does not contain an additional rdf:Description, because it is _linking_ to another resource through rdf:resource, instead of _describing_ a resource through rdf:about. If we had more facts to add about the cover page (e.g. artist, etc.), we could swap these properties around and add another rdf:Description.

You can also validate this example using the w3c RDF validator here: https://www.w3.org/RDF/Validator/rdfval?URI=https%3A%2F%2Fraw.githubusercontent.com%2Fcomicmeta%2FComicBookOntology%2Fmaster%2Fexamples%2Frdf-xml%2Fexample-x-daredevil.rdf&PARSE=Parse+URI%3A+&TRIPLES_AND_GRAPH=PRINT_BOTH&FORMAT=PNG_EMBED

If the RDF input is valid, this tool will output the RDF triples, and a PNG graph.
